-- Query 1: Find all posts with the tag 'DIY'.
SELECT
POST.TITLE,
TAG.TAG_NAME
FROM POST
INNER JOIN POST_TAG
ON POST.POST_ID = POST_TAG.POST_ID
INNER JOIN TAG
ON POST_TAG.TAG_ID = TAG.TAG_ID
WHERE TAG.TAG_NAME = 'DIY'