-- Query 12: List all posts that have photos, together with their comments (if any).
SELECT
POST.POST_ID,
POST.TITLE,
PERSON.FIRST_NAME AS AUTHOR,
POST_COMMENT.COMMENT AS COMMENT,
COMMENTER.FIRST_NAME AS COMMENTER
FROM POST
INNER JOIN PERSON
ON PERSON.PERSON_ID = POST.PERSON_ID
INNER JOIN POST_PHOTO
ON POST_PHOTO.POST_ID = POST.POST_ID
LEFT JOIN POST_COMMENT
ON POST_COMMENT.POST_ID = POST.POST_ID
LEFT JOIN PERSON AS COMMENTER
ON COMMENTER.PERSON_ID = POST_COMMENT.PERSON_ID
WHERE POST_PHOTO.POST_ID IS NOT NULL
GROUP BY POST.POST_ID, POST_COMMENT.PERSON_ID, POST_COMMENT.COMMENT
ORDER BY POST.POST_ID;