-- Query 13: List every post with its counts of reads, likes and comments (zero when none).
SELECT
POST.POST_ID,
POST.TITLE,

IFNULL((SELECT COUNT(*) FROM READ_POST WHERE READ_POST.POST_ID = POST.POST_ID),0) AS 'Reads',
IFNULL((SELECT COUNT(*) FROM POST_LIKE WHERE POST_LIKE.POST_ID = POST.POST_ID),0) AS 'Likes',
IFNULL((SELECT COUNT(*) FROM POST_COMMENT WHERE POST_COMMENT.POST_ID = POST.POST_ID),0) AS 'Comments'

FROM POST
GROUP BY POST.POST_ID