-- Query 14: List all photos classified as either profile photos or post photos.
SELECT 
PHOTO.PHOTO_ID, 
PHOTO.CAPTION,
PHOTO.FILE_NAME,
'Profile Photo' AS TYPE
FROM PHOTO
INNER JOIN PERSON AS ON_PROFILE_PHOTO
ON PHOTO.PHOTO_ID = ON_PROFILE_PHOTO.PROFILE_PHOTO_ID

UNION ALL

SELECT 
PHOTO.PHOTO_ID, 
PHOTO.CAPTION,
PHOTO.FILE_NAME,
'Post Photo' AS TYPE 
FROM PHOTO
INNER JOIN POST_PHOTO AS POSTED_PHOTO
ON PHOTO.PHOTO_ID = POSTED_PHOTO.PHOTO_ID 