-- Query 4: Which posts have no tags?
SELECT
POST.TITLE AS 'Title',
COUNT(POST_TAG.POST_ID) AS 'Number of Tags'
FROM POST
LEFT JOIN POST_TAG
ON POST.POST_ID = POST_TAG.POST_ID
LEFT JOIN TAG
ON POST_TAG.TAG_ID = TAG.TAG_ID
GROUP BY POST.POST_ID
HAVING COUNT(POST_TAG.POST_ID) = 0
ORDER BY COUNT(POST_TAG.POST_ID) DESC;