-- Query 6: Find all posts that have been read.
SELECT
POST.POST_ID,
POST.TITLE,
PERSON.FIRST_NAME
FROM PERSON
INNER JOIN POST
ON POST.PERSON_ID = PERSON.PERSON_ID
INNER JOIN READ_POST 
ON POST.POST_ID = READ_POST.POST_ID
GROUP BY POST.POST_ID
ORDER BY POST.POST_ID
