-- Query 8: Find all posts edited after they were created (last_modified_date > created_date).
SELECT
POST.POST_ID,
POST.TITLE,
PERSON.FIRST_NAME,
CAST(POST.CREATED_DATE AS DATE) AS CREATED_DATE,
CAST(POST.LAST_MODIFIED_DATE AS DATE) AS LAST_MODIFIED_DATE
FROM PERSON
INNER JOIN POST
ON POST.PERSON_ID = PERSON.PERSON_ID
WHERE POST.LAST_MODIFIED_DATE > POST.CREATED_DATE
ORDER BY POST.POST_ID