-- Query 9: Find all posts that have no photos.
SELECT
POST.POST_ID,
POST.TITLE,
PERSON.FIRST_NAME
FROM PERSON
INNER JOIN POST
ON POST.PERSON_ID = PERSON.PERSON_ID
LEFT JOIN POST_PHOTO
ON POST_PHOTO.POST_ID = POST.POST_ID
WHERE POST_PHOTO.POST_ID IS NULL
ORDER BY POST.POST_ID